# Generated by Django 2.1.5 on 2019-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190222_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
